#!/bin/bash

# =============================================================================
# Thesis Project - Claude Code Alias Setup Script
# =============================================================================
# Purpose: Automatically add thesis-code and related aliases to shell config
# Author: Auto-generated for thesis workflow
# Date: 2026-05-20
# =============================================================================

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print functions
print_header() {
    echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

# =============================================================================
# Main Setup
# =============================================================================

print_header "Thesis Workflow - Alias Setup"

echo ""
echo "This script will add the following commands to your shell:"
echo "  • thesis-code    - Start Claude Code with context"
echo "  • thesis-cd      - Navigate to thesis directory"
echo "  • thesis-status  - View current status"
echo "  • thesis-context - View project context"
echo "  • thesis-commit  - Commit & push status files"
echo "  • thesis-help    - Show available commands"
echo ""

# Detect shell
CURRENT_SHELL=$(basename "$SHELL")
print_info "Detected shell: $CURRENT_SHELL"

# Determine config file
if [[ "$CURRENT_SHELL" == "zsh" ]]; then
    CONFIG_FILE="$HOME/.zshrc"
elif [[ "$CURRENT_SHELL" == "bash" ]]; then
    if [[ -f "$HOME/.bashrc" ]]; then
        CONFIG_FILE="$HOME/.bashrc"
    else
        CONFIG_FILE="$HOME/.bash_profile"
    fi
else
    print_error "Unsupported shell: $CURRENT_SHELL"
    print_info "Please manually add aliases from CLAUDE_CODE_ALIAS_SETUP.md"
    exit 1
fi

print_info "Using config file: $CONFIG_FILE"

# Check if config file exists
if [[ ! -f "$CONFIG_FILE" ]]; then
    print_warning "Config file not found. Creating: $CONFIG_FILE"
    touch "$CONFIG_FILE"
fi

# Check if aliases already exist
if grep -q "# Thesis Project Alias" "$CONFIG_FILE"; then
    print_warning "Thesis aliases already exist in $CONFIG_FILE"
    echo ""
    read -p "Do you want to replace them? (y/N): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_info "Skipping alias installation"
        exit 0
    fi

    print_info "Removing old aliases..."
    # Remove old section (between markers)
    sed -i.bak '/# Thesis Project Alias/,/# End Thesis Aliases/d' "$CONFIG_FILE"
    print_success "Old aliases removed (backup saved as ${CONFIG_FILE}.bak)"
fi

# Get thesis directory
THESIS_DIR="$HOME/Desktop/Master_Thesis/Labs/multi-cloud-optimization"

if [[ ! -d "$THESIS_DIR" ]]; then
    print_error "Thesis directory not found: $THESIS_DIR"
    read -p "Enter correct thesis directory path: " THESIS_DIR
    if [[ ! -d "$THESIS_DIR" ]]; then
        print_error "Directory still not found: $THESIS_DIR"
        exit 1
    fi
fi

print_success "Thesis directory found: $THESIS_DIR"

# Create alias section
print_info "Adding aliases to $CONFIG_FILE..."

cat >> "$CONFIG_FILE" << 'EOF'

# ========================================
# Thesis Project Alias
# Auto-generated by setup_thesis_alias.sh
# ========================================

# Quick access to thesis directory
alias thesis-cd='cd ~/Desktop/Master_Thesis/Labs/multi-cloud-optimization'

# Claude Code with automatic context loading
thesis-code() {
    local THESIS_DIR="$HOME/Desktop/Master_Thesis/Labs/multi-cloud-optimization"
    cd "$THESIS_DIR" || {
        echo "❌ Error: Thesis directory not found at $THESIS_DIR"
        return 1
    }

    echo "📂 Navigated to thesis directory"
    echo "📄 Auto-loading context files:"
    echo "   - PROJECT_CONTEXT.md"
    echo "   - CURRENT_STATUS.md"
    echo ""

    # Check if context files exist
    if [[ ! -f "PROJECT_CONTEXT.md" ]]; then
        echo "⚠️  Warning: PROJECT_CONTEXT.md not found!"
    fi

    if [[ ! -f "CURRENT_STATUS.md" ]]; then
        echo "⚠️  Warning: CURRENT_STATUS.md not found!"
    fi

    echo "🚀 Starting Claude Code..."
    echo ""

    # Start Claude Code
    claude
}

# Quick status check
thesis-status() {
    local THESIS_DIR="$HOME/Desktop/Master_Thesis/Labs/multi-cloud-optimization"
    if [[ -f "$THESIS_DIR/CURRENT_STATUS.md" ]]; then
        cat "$THESIS_DIR/CURRENT_STATUS.md"
    else
        echo "❌ CURRENT_STATUS.md not found!"
    fi
}

# Quick context view
thesis-context() {
    local THESIS_DIR="$HOME/Desktop/Master_Thesis/Labs/multi-cloud-optimization"
    if [[ -f "$THESIS_DIR/PROJECT_CONTEXT.md" ]]; then
        cat "$THESIS_DIR/PROJECT_CONTEXT.md" | head -50
        echo ""
        echo "📄 (Showing first 50 lines. Use 'cat PROJECT_CONTEXT.md' for full file)"
    else
        echo "❌ PROJECT_CONTEXT.md not found!"
    fi
}

# Commit current status
thesis-commit() {
    local THESIS_DIR="$HOME/Desktop/Master_Thesis/Labs/multi-cloud-optimization"
    cd "$THESIS_DIR" || return 1

    git add CURRENT_STATUS.md PROJECT_CONTEXT.md

    if [[ -n "$1" ]]; then
        git commit -m "$1"
    else
        git commit -m "Update status - $(date +%Y-%m-%d)"
    fi

    git push
    echo "✅ Status files committed and pushed!"
}

# Quick help
thesis-help() {
    echo "🎓 Thesis Command Helpers"
    echo ""
    echo "Available commands:"
    echo "  thesis-cd        - Navigate to thesis directory"
    echo "  thesis-code      - Start Claude Code with context"
    echo "  thesis-status    - View current status"
    echo "  thesis-context   - View project context"
    echo "  thesis-commit    - Commit & push status files"
    echo "  thesis-help      - Show this help"
    echo ""
    echo "Example usage:"
    echo "  $ thesis-code"
    echo "  $ thesis-status"
    echo "  $ thesis-commit 'Daily update'"
}

# End Thesis Aliases
EOF

print_success "Aliases added to $CONFIG_FILE"

# Reload configuration
print_info "Reloading shell configuration..."
# shellcheck disable=SC1090
source "$CONFIG_FILE"

print_success "Configuration reloaded!"

echo ""
print_header "Setup Complete! 🎉"
echo ""
print_success "Available commands:"
echo "  • thesis-code    - Start Claude Code with context"
echo "  • thesis-cd      - Navigate to thesis directory"
echo "  • thesis-status  - View current status"
echo "  • thesis-context - View project context"
echo "  • thesis-commit  - Commit & push status files"
echo "  • thesis-help    - Show available commands"
echo ""
print_info "Try running: thesis-help"
echo ""
print_warning "Note: If commands don't work in current terminal, run:"
echo "  source $CONFIG_FILE"
echo ""
print_warning "Or open a new terminal window."
echo ""
print_success "Happy thesis writing! 🚀"
